#!/bin/bash

# Set the desired tag key and value
TAG_KEY="your_tag_key"
TAG_VALUE="your_tag_value"

# Retrieve the list of snapshots with the specified tag key and value
SNAPSHOT_INFO=$(aws ec2 describe-snapshots --filters "Name=tag:${TAG_KEY},Values=${TAG_VALUE}" --output json)

# Extract the relevant information from the snapshot info
SNAPSHOT_IDS=$(echo "$SNAPSHOT_INFO" | jq -r '.Snapshots[].SnapshotId')
DESCRIPTIONS=$(echo "$SNAPSHOT_INFO" | jq -r '.Snapshots[].Description')
CREATION_DATES=$(echo "$SNAPSHOT_INFO" | jq -r '.Snapshots[].StartTime')

# Print the list of snapshots
echo "Snapshots with Tag: ${TAG_KEY}=${TAG_VALUE}"
echo "--------------------------------------"
echo "Snapshot ID | Description | Creation Date"
echo "--------------------------------------"
for i in $(seq 0 $((${#SNAPSHOT_IDS[@]}-1))); do
  SNAPSHOT_ID="${SNAPSHOT_IDS[i]}"
  DESCRIPTION="${DESCRIPTIONS[i]}"
  CREATION_DATE="${CREATION_DATES[i]}"
  echo "$SNAPSHOT_ID | $DESCRIPTION | $CREATION_DATE"
done
echo "--------------------------------------"
